# Generated by Django 5.0.4 on 2024-08-28 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome1', models.CharField(max_length=100)),
                ('cpf1', models.CharField(max_length=11)),
                ('nome2', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf2', models.CharField(blank=True, max_length=11, null=True)),
                ('nome3', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf3', models.CharField(blank=True, max_length=11, null=True)),
                ('nome4', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf4', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('cpf', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='CPF')),
                ('complete_name', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('id_name', models.CharField(max_length=100, verbose_name='Nome no crachá')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefone')),
                ('city', models.CharField(max_length=30, verbose_name='Cidade')),
                ('state', models.CharField(max_length=30, verbose_name='UF')),
                ('is_deficient', models.BooleanField(default=False, null=True, verbose_name='Tem deficiência?')),
                ('deficiency', models.CharField(blank=True, default='', max_length=50, verbose_name='Qual a deficiência?')),
                ('person_type', models.IntegerField(verbose_name='Tipo de Pessoa')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Dia em que foi cadastrado')),
                ('payed', models.BooleanField(default=False, verbose_name='Pago')),
                ('work', models.FileField(blank=True, null=True, upload_to='uploads/work/%Y/%m/%d/', verbose_name='Trabalho Submetido')),
                ('subscripted_courses', models.TextField(default={}, verbose_name='Mini Cursos Inscritos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PosGradStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100, verbose_name='Area de atuação')),
                ('institution', models.CharField(max_length=100, verbose_name='Instituição')),
                ('course_id', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Comprovante de vínculo')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.person')),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_name', models.CharField(max_length=100, verbose_name='Nome da Empresa')),
                ('enterprise', models.CharField(choices=[('MIN', 'Mineradora'), ('FOR', 'Fornecedora do Setor Mineral'), ('ACA', 'Academia'), ('ONG', 'ONG / Terceiro Setor'), ('POD', 'Poder Público'), ('ENT', 'Entidades'), ('CON', 'Consultoria'), ('AUT', 'Autônomo'), ('OUT', 'Outros')], max_length=3, verbose_name='Empresa')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.person')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100, verbose_name='Curso')),
                ('institution', models.CharField(max_length=100, verbose_name='Instituição')),
                ('course_id', models.CharField(max_length=50, verbose_name='Número de matrícula')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.person')),
            ],
        ),
    ]
