# Generated by Django 5.0.4 on 2024-04-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=30, verbose_name='CPF')),
                ('complete_name', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('id_name', models.CharField(max_length=30, verbose_name='Nome no Crachá')),
                ('email', models.CharField(max_length=30, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefone')),
                ('city', models.CharField(max_length=30, verbose_name='Cidade')),
                ('state', models.CharField(max_length=30, verbose_name='UF')),
                ('is_deficient', models.BooleanField(default=False, verbose_name='Tem deficiência?')),
                ('deficiency', models.CharField(max_length=50, verbose_name='Qual a deficiência?')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Dia em que foi cadastrado')),
            ],
        ),
    ]
