# Generated by Django 5.0.4 on 2024-04-15 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='person',
            name='deficiency',
            field=models.CharField(default='', max_length=50, verbose_name='Qual a deficiência?'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.CreateModel(
            name='PosGradStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100, verbose_name='Area')),
                ('institution', models.CharField(max_length=100, verbose_name='Instituição')),
                ('course_id', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Comprovante de vínculo')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.person')),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise', models.CharField(choices=[('MIN', 'Mineradora'), ('FOR', 'Fornecedora do Setor Mineral'), ('ACA', 'Academia'), ('ONG', 'ONG / Terceiro Setor'), ('POD', 'Poder Público'), ('ENT', 'Entidades'), ('CON', 'Consultoria'), ('AUT', 'Autônomo'), ('OUT', 'Outros')], max_length=3, verbose_name='Empresa')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.person')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100, verbose_name='Curso')),
                ('institution', models.CharField(max_length=100, verbose_name='Instituição')),
                ('course_id', models.CharField(max_length=50, verbose_name='Número de matrícula')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.person')),
            ],
        ),
    ]
