# Generated by Django 5.0.4 on 2024-04-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_person_id_alter_person_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='complete_name',
            field=models.CharField(max_length=100, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='deficiency',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Qual a deficiência?'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id_name',
            field=models.CharField(max_length=30, verbose_name='Nome no crachá'),
        ),
        migrations.AlterField(
            model_name='posgradstudent',
            name='area',
            field=models.CharField(max_length=100, verbose_name='Area de atuação'),
        ),
    ]
